#!/usr/bin/env python3
"""
Mineru → EPUB Converter (v2 — pattern-driven, zero semantic assumptions)

Two modes:

  --profile           Scan Mineru data, detect footnote patterns, output JSON.
                      No semantic labelling — just character-group statistics.
  
  --convert           Generate EPUB. Requires --footnote-config (output of
                      LLM analysis after --profile) plus optional --config
                      for chapter definitions.

The script itself makes ZERO assumptions about what a footnote "means".
All semantic decisions (label, display style, ordering) come from the
footnote-config JSON, which is generated by the LLM Agent following the
guidance in SKILL.md.
"""

import json, re, glob, sys, os, argparse
from pathlib import Path
from datetime import datetime
from collections import Counter, defaultdict
import html
import zipfile
from PIL import Image

# ── Constants (no semantic assumptions) ──────────────────────

CIRCLED_CHARS = '①②③④⑤⑥⑦⑧⑨⑩⑪⑫⑬⑭⑮'
CIRCLE_TO_NUM = {c: str(i) for i, c in enumerate(CIRCLED_CHARS, 1)}
NUM_TO_CIRCLE = {v: k for k, v in CIRCLE_TO_NUM.items()}
CIRCLED_RE = re.compile(r'[' + CIRCLED_CHARS + r']+')

DEFAULT_CSS = '''
body {
    font-family: "Songti SC", "Noto Serif CJK SC", "STSong", "SimSun", serif;
    line-height: 1.85; margin: 0; padding: 0.5em 0.8em; text-align: justify;
}
h1 { text-align: center; font-size: 1.5em; font-weight: bold;
     margin: 2.5em 0 1.2em 0; page-break-before: always; line-height: 1.4; }
h2 { text-align: center; font-size: 1.2em; margin: 1.5em 0 0.8em 0; font-weight: bold; }
p { text-indent: 2em; margin: 0.2em 0; }
sup a { text-decoration: none; color: #555; font-size: 0.7em; vertical-align: super; line-height: 0; }
figure { text-align: center; margin: 1.5em 0; page-break-inside: avoid; }
figure img { max-width: 95%; height: auto; }
aside { margin: 0.3em 0; padding: 0.2em 0.5em; font-size: 0.8em; border-top: 1px dotted #bbb; }
aside p { text-indent: 0; margin: 0.1em 0; font-size: 0.9em; }
aside a { text-decoration: none; color: #555; }
.fn-section { margin-top: 2em; border-top: 2px solid #888; padding-top: 0.6em; }
.fn-section h3 { font-size: 0.95em; text-align: left; font-weight: bold; }
.cover-image { text-align: center; margin: 1em 0; page-break-after: always; }
.cover-image img { max-width: 100%; height: auto; }
.title-page { text-align: center; page-break-before: always; margin-top: 15%; }
.title-page h1 { font-size: 1.8em; page-break-before: avoid; margin-bottom: 0.5em; }
.title-page .subtitle { font-size: 1em; color: #555; }
.title-page .author { font-size: 1.1em; margin-top: 2em; }
.toc-part   { text-indent: 0; font-weight: bold; font-size: 1.05em;
              margin: 1.2em 0 0.4em 0; text-align: left; }
.toc-chapter { text-indent: 1.5em; margin: 0.15em 0; }
.toc-section  { text-indent: 0; font-weight: bold;
                margin: 0.8em 0 0.3em 0; }
'''

# ── Helpers ─────────────────────────────────────────────────

def is_sentence_end(text):
    """Check if text ends with sentence-ending punctuation."""
    if not text:
        return True
    last = text.rstrip()[-1] if text.rstrip() else ''
    return last in '。！？' + '"\'' + '」』）)】〕' + '：；'  # ：； are weaker but still boundaries


def is_continuation_start(text):
    """Check if text looks like a mid-sentence continuation rather than a new paragraph."""
    if not text or not text.strip():
        return True
    t = text.strip()
    # New paragraph indicators (Chinese)
    new_para_starters = [
        '首先', '其次', '最后', '第一', '第二', '第三', '另外', '此外',
        '但是', '然而', '不过', '因此', '所以', '于是', '总之', '综上所述',
        '例如', '比如', '换句话', '也就是', '这意味', '值得注意', '需要说明',
        '当然', '显然', '事实上', '实际上', '与此同', '另一方', '相反',
        '无论如', '在此基', '从某种', '在某种', '同样', '与此', '尽管',
        '问题在', '结果是', '可以肯', '毫无疑', '众所周', '有趣的是',
        '简而言', '回到', '那么', '现在', '最终', '本章', '本节',
        '这里', '我们', '大家', '读者', '在前面', '在前文', '在前一',
    ]
    # If starts with any of these, it's a new paragraph
    for s in new_para_starters:
        if t.startswith(s):
            return False
    # If starts with quote or parenthetical (dialogue continuation)
    if t[0] in '"''「『（(':
        return True
    # If first sentence is very short (tail fragment), it's a continuation
    first_period = min((t.find(p) for p in '。！？' if p in t), default=-1)
    if first_period > 0 and first_period < 15:
        return True
    # Short text (< 30 chars) ending mid-sentence is likely continuation
    if len(t) < 30 and not is_sentence_end(t):
        return True
    return False


def merge_broken_paragraphs(parts):
    """Merge consecutive <p> elements where the first ends mid-sentence
    and the second starts as a continuation (page-break artifact)."""
    if len(parts) < 2:
        return parts
    
    result = []
    i = 0
    while i < len(parts):
        part = parts[i]
        
        # Check if this is a <p> that might need merging with the next <p>
        if part.startswith('<p>') and i + 1 < len(parts):
            next_part = parts[i + 1]
            if next_part.startswith('<p>'):
                # Strip HTML to check text content
                this_text = re.sub(r'<[^>]+>', '', part[3:-4])  # remove <p> and </p>
                next_text = re.sub(r'<[^>]+>', '', next_part[3:-4])
                
                # Merge if: this ends mid-sentence OR next starts as continuation
                if (not is_sentence_end(this_text) or is_continuation_start(next_text)):
                    # Merge: strip </p> from this and <p> from next
                    merged = part[:-4] + next_part[3:]
                    result.append(merged)
                    i += 2
                    continue
        
        result.append(part)
        i += 1
    
    return result


def load_pages(part_dirs):
    """Load all Mineru part directories. Returns [{abs_page, blocks, label}]."""
    all_pages = []
    for part_dir in part_dirs:
        json_files = glob.glob(f"{part_dir}/*_content_list_v2.json")
        if not json_files:
            raise FileNotFoundError(f"No content_list_v2.json in {part_dir}")
        with open(json_files[0], "r") as f:
            pages = json.load(f)
        offset = len(all_pages)
        for i, blocks in enumerate(pages):
            all_pages.append({"abs_page": offset + i + 1, "blocks": blocks, "label": part_dir})
    all_pages.sort(key=lambda x: x["abs_page"])
    return all_pages


def character_group(char):
    """Classify a character into a group for pattern clustering."""
    if char in CIRCLED_CHARS:
        return "circled_ideograph"
    if '\u4e00' <= char <= '\u9fff' or '\u3040' <= char <= '\u30ff':
        return "cjk"
    if char.isdigit():
        return "digit"
    if char.isalpha():
        return "latin"
    if char in '*†‡§¶#':
        return "symbol"
    return "other"


def detect_body_language(text):
    """Return {cjk, latin, digit, other} ratios for a text sample."""
    if not text:
        return {"cjk": 0, "latin": 0, "digit": 0, "other": 0}
    counts = {"cjk": 0, "latin": 0, "digit": 0, "other": 0}
    for ch in text:
        g = character_group(ch)
        if g == "cjk" or g == "circled_ideograph":
            counts["cjk"] += 1
        elif g == "latin":
            counts["latin"] += 1
        elif g == "digit":
            counts["digit"] += 1
        else:
            counts["other"] += 1
    total = max(sum(counts.values()), 1)
    return {k: round(v / total, 3) for k, v in counts.items()}


def compress_image(src, dst, max_width=1200, quality=75):
    """Compress and optionally resize an image."""
    img = Image.open(src)
    w, h = img.size
    if w > max_width:
        img = img.resize((max_width, int(h * max_width / w)), Image.LANCZOS)
    if img.mode == 'RGBA':
        bg = Image.new('RGB', img.size, (255, 255, 255))
        bg.paste(img, mask=img.split()[3])
        img = bg
    elif img.mode != 'RGB':
        img = img.convert('RGB')
    img.save(dst, 'JPEG', quality=quality, optimize=True)
    return img.size


def should_include_image(img_path):
    """Filter out tiny decorative markers."""
    try:
        img = Image.open(img_path)
        w, h = img.size
        return not (w <= 120 and h <= 120 and img_path.stat().st_size < 4000)
    except Exception:
        return False

# ── Profile mode ────────────────────────────────────────────

def profile_footnotes(all_pages):
    """
    Scan the entire book and detect footnote patterns.
    Returns a dict with detected_patterns key.
    Makes ZERO semantic assumptions — just reports observable statistics.
    """
    # ── Collect all markers ──
    marker_groups = defaultdict(list)  # char_group → [(abs_page, block_idx, item_idx, raw_text)]

    for pdata in all_pages:
        ap = pdata["abs_page"]
        for bi, b in enumerate(pdata["blocks"]):
            if b.get("type") not in ("paragraph", "title"):
                continue
            ck = "paragraph_content" if b["type"] == "paragraph" else "title_content"
            items = b.get("content", {}).get(ck, [])
            
            for ci, item in enumerate(items):
                if not isinstance(item, dict):
                    continue
                raw = item.get("content", "")
                
                if item.get("type") == "equation_inline":
                    # Parse ^{...} wrapper
                    m = re.match(r'\^\{([^}]+)\}', raw.strip())
                    inner = m.group(1) if m else raw.strip()
                    if inner and len(inner) <= 5:
                        group = character_group(inner[0])
                        ctx = "".join(it.get("content", "") for it in items if isinstance(it, dict))
                        marker_groups[group].append({
                            "abs_page": ap, "block_idx": bi, "item_idx": ci,
                            "raw": raw, "inner": inner,
                            "context": ctx[max(0, ctx.find(raw)-15):ctx.find(raw)+20] if raw in ctx else raw
                        })
                
                elif item.get("type") == "text":
                    # Text-embedded markers: look for ^{number}, circled chars, etc.
                    for m in re.finditer(r'\^\{([^}]+)\}', raw):
                        inner = m.group(1)
                        if inner and len(inner) <= 5:
                            group = character_group(inner[0])
                            marker_groups[group].append({
                                "abs_page": ap, "block_idx": bi, "item_idx": ci,
                                "raw": m.group(0), "inner": inner,
                                "context": raw[max(0,m.start()-15):m.end()+15]
                            })
                    for m in CIRCLED_RE.finditer(raw):
                        inner = m.group(0)
                        group = character_group(inner[0])
                        marker_groups[group].append({
                            "abs_page": ap, "block_idx": bi, "item_idx": ci,
                            "raw": inner, "inner": inner,
                            "context": raw[max(0,m.start()-15):m.end()+15]
                        })

    # ── Collect all body prefixes ──
    body_groups = defaultdict(list)  # char_group → [{abs_page, prefix, full_text}]

    for pdata in all_pages:
        ap = pdata["abs_page"]
        for bi, b in enumerate(pdata["blocks"]):
            if b.get("type") != "page_footnote":
                continue
            items = b.get("content", {}).get("page_footnote_content", [])
            if not items:
                continue
            
            # Strategy 1: split on equation_inline boundaries
            current_prefix = None
            current_text = []
            for item in items:
                if not isinstance(item, dict):
                    continue
                content = item.get("content", "")
                if item.get("type") == "equation_inline":
                    if current_prefix is not None:
                        full = "".join(current_text).strip()
                        group = character_group(current_prefix[0]) if current_prefix else "unknown"
                        body_groups[group].append({
                            "abs_page": ap, "prefix": current_prefix,
                            "full_text": full, "text_length": len(full)
                        })
                    m = re.match(r'\^\{([^}]+)\}', content.strip())
                    current_prefix = m.group(1) if m else content.strip()
                    current_text = []
                elif item.get("type") == "text":
                    current_text.append(content)
            # Flush last
            if current_prefix is not None:
                full = "".join(current_text).strip()
                group = character_group(current_prefix[0]) if current_prefix else "unknown"
                body_groups[group].append({
                    "abs_page": ap, "prefix": current_prefix,
                    "full_text": full, "text_length": len(full)
                })
            
            # Strategy 2: fallback for text-only blocks
            if current_prefix is None:
                text = "".join(it.get("content", "") for it in items
                              if isinstance(it, dict) and it.get("type") == "text").strip()
                if text and len(text) > 0:
                    first_char = text[0]
                    group = character_group(first_char)
                    # Extract prefix
                    if CIRCLED_RE.match(first_char):
                        prefix = CIRCLED_RE.match(text).group(0)
                    elif first_char.isdigit():
                        prefix = re.match(r'^(\d+)', text).group(1)
                    else:
                        prefix = first_char
                    body_groups[group].append({
                        "abs_page": ap, "prefix": prefix,
                        "full_text": text, "text_length": len(text)
                    })

    # ── Build pattern summary ──
    patterns = []
    all_groups = set(marker_groups.keys()) | set(body_groups.keys())

    for gid, group_name in enumerate(sorted(all_groups), 1):
        markers = marker_groups.get(group_name, [])
        bodies = body_groups.get(group_name, [])
        
        if not markers and not bodies:
            continue
        
        # Determine character set and format
        marker_chars = set()
        for m in markers:
            marker_chars.update(m["inner"])
        marker_chars = "".join(sorted(marker_chars, key=lambda c: ord(c)))
        
        # Determine format
        if all(c in CIRCLED_CHARS for c in marker_chars):
            fmt = "circled_ideograph"
        elif all(c.isdigit() for c in marker_chars):
            fmt = "superscript_digit"
        elif all(c in '*†‡§¶#' for c in marker_chars):
            fmt = "symbol"
        else:
            fmt = "mixed"
        
        # Body samples
        body_samples = [b for b in bodies if b["full_text"]]
        combined_text = " ".join(b["full_text"][:200] for b in body_samples[:20])
        lang = detect_body_language(combined_text)
        avg_len = round(sum(b["text_length"] for b in body_samples) / max(len(body_samples), 1), 1)
        
        # Context samples from markers
        ctx_samples = [m["context"] for m in markers[:10]]
        
        patterns.append({
            "id": "p%d" % gid,
            "marker_chars": marker_chars,
            "marker_format": fmt,
            "ref_count": len(markers),
            "body_count": len(bodies),
            "body_samples": [b["full_text"][:150] for b in body_samples[:6] if b["full_text"]],
            "context_samples": ctx_samples[:5],
            "body_language": lang,
            "body_avg_length": avg_len,
            "pages_with_markers": len(set(m["abs_page"] for m in markers)),
            "pages_with_bodies": len(set(b["abs_page"] for b in bodies)),
        })

    return {
        "detected_patterns": patterns,
        "total_pages": len(all_pages),
        "total_markers": sum(len(marker_groups[g]) for g in marker_groups),
        "total_bodies": sum(len(body_groups[g]) for g in body_groups),
    }


# ── Convert mode: footnote extraction ───────────────────────

def extract_footnotes(all_pages, patterns):
    """
    patterns: list of {id, marker_regex, marker_eq_regex, body_prefix_regex}
    Returns: all_refs, all_contents (both lists of tuples with pattern_id at end)
    """
    all_refs, all_contents = [], []
    refs_by_page, contents_by_page = defaultdict(list), defaultdict(list)
    
    # Pre-compile regexes
    for p in patterns:
        p["_marker_re"] = re.compile(p["marker_regex"]) if p.get("marker_regex") else None
        p["_marker_eq_re"] = re.compile(p["marker_eq_regex"]) if p.get("marker_eq_regex") else None
        p["_body_prefix_re"] = re.compile(p["body_prefix_regex"]) if p.get("body_prefix_regex") else None
    
    for pdata in all_pages:
        ap = pdata["abs_page"]
        blocks = pdata["blocks"]
        
        for pi, pat in enumerate(patterns):
            pid = pat["id"]
            
            # ── Ref extraction: equation_inline ──
            for bi, b in enumerate(blocks):
                if b.get("type") not in ("paragraph", "title"):
                    continue
                ck = "paragraph_content" if b["type"] == "paragraph" else "title_content"
                items = b.get("content", {}).get(ck, [])
                for ci, item in enumerate(items):
                    if not isinstance(item, dict) or item.get("type") != "equation_inline":
                        continue
                    raw = item.get("content", "").strip()
                    if pat["_marker_eq_re"]:
                        for m in pat["_marker_eq_re"].finditer(raw):
                            inner = m.group(1) if m.lastindex else m.group(0)
                            ctx = "".join(it.get("content", "") for it in items if isinstance(it, dict))
                            all_refs.append((ap, bi, ci, inner, inner,
                                             ctx[max(0, ctx.find(raw)-15):ctx.find(raw)+20], pid))
                            refs_by_page[ap].append(len(all_refs) - 1)
                
                # ── Ref extraction: text-embedded ──
                if any(r[0] == ap and r[1] == bi and r[6] == pid for r in all_refs):
                    continue  # already captured via equation_inline in this block
                # Scan full concatenated text (like V1) but track item-level position
                all_text = "".join(it.get("content", "") for it in items if isinstance(it, dict))
                if pat["_marker_re"]:
                    for m in pat["_marker_re"].finditer(all_text):
                        inner = m.group(1) if m.lastindex else m.group(0)
                        pos = m.start()
                        # Find which text item contains this position
                        ci = -1  # Default: text-embedded marker
                        offset = 0
                        for idx, item in enumerate(items):
                            if isinstance(item, dict) and item.get("type") == "text":
                                ic = item.get("content", "")
                                if offset <= pos < offset + len(ic):
                                    ci = idx
                                    break
                                offset += len(ic)
                        # Use -1 to signal text-embedded (distinguishes from equation_inline ci >= 0)
                        all_refs.append((ap, bi, -1, inner, inner,
                                         all_text[max(0, pos-15):m.end()+15], pid))
                        refs_by_page[ap].append(len(all_refs) - 1)
        
        # ── Content extraction ──
        for bi, b in enumerate(blocks):
            if b.get("type") != "page_footnote":
                continue
            items = b.get("content", {}).get("page_footnote_content", [])
            if not items:
                continue
            
            # Strategy: split on equation_inline boundaries
            current_num = None
            current_pid = None
            current_text = []
            
            for item in items:
                if not isinstance(item, dict):
                    continue
                content = item.get("content", "")
                
                if item.get("type") == "equation_inline":
                    if current_num is not None:
                        full_text = "".join(current_text).strip()
                        all_contents.append((ap, current_num, current_num, full_text, current_pid))
                        contents_by_page[ap].append(len(all_contents) - 1)
                    
                    m = re.match(r'\^\{([^}]+)\}', content.strip())
                    inner = m.group(1) if m else content.strip()
                    current_num = inner
                    # Find which pattern this belongs to
                    current_pid = None
                    for pat in patterns:
                        if pat["_body_prefix_re"] and pat["_body_prefix_re"].match(inner):
                            current_pid = pat["id"]
                            break
                    if current_pid is None:
                        current_pid = patterns[0]["id"] if patterns else "unknown"
                    current_text = []
                
                elif item.get("type") == "text":
                    current_text.append(content)
            
            # Flush last
            if current_num is not None:
                full_text = "".join(current_text).strip()
                all_contents.append((ap, current_num, current_num, full_text, current_pid))
                contents_by_page[ap].append(len(all_contents) - 1)
            
            # Fallback: text-only blocks
            if current_num is None:
                text = "".join(it.get("content", "") for it in items
                              if isinstance(it, dict) and it.get("type") == "text").strip()
                if text:
                    for pat in patterns:
                        if pat["_body_prefix_re"]:
                            m = pat["_body_prefix_re"].match(text)
                            if m:
                                raw = m.group(0)
                                # Multi-number splitting for digit-based patterns
                                if pat.get("multi_number_split") and raw.isdigit():
                                    parts = re.split(r'(?<=\S)\s+(?=\d+\s)', text)
                                    if len(parts) > 1:
                                        for part in parts:
                                            pm = pat["_body_prefix_re"].match(part)
                                            if pm:
                                                r = pm.group(0)
                                                all_contents.append((ap, r, r, part.strip(), pat["id"]))
                                                contents_by_page[ap].append(len(all_contents) - 1)
                                        break
                                all_contents.append((ap, raw, raw, text.strip(), pat["id"]))
                                contents_by_page[ap].append(len(all_contents) - 1)
                                break
    
    return all_refs, all_contents, dict(refs_by_page), dict(contents_by_page)


def filter_enumeration_refs(all_refs, all_pages, refs_by_page):
    """Remove circled-number refs that are enumeration markers (not footnotes).
    
    Detection: consecutive circled numbers (①②③...) at BLOCK-START positions
    across same or adjacent pages → author's enumerated list.
    
    Conservative: only removes when 2+ sequential items exist, each at position 0
    in its block. Real footnotes appear inline (mid-sentence or after punctuation),
    not at paragraph start.
    """
    # Build block-start lookup
    block_is_start = {}
    for pdata in all_pages:
        ap = pdata["abs_page"]
        for bi, b in enumerate(pdata["blocks"]):
            if b.get("type") not in ("paragraph", "title"):
                continue
            items = b.get("content",{}).get("paragraph_content",[])
            full = "".join(it.get("content","") for it in items if isinstance(it, dict))
            block_is_start[(ap, bi)] = bool(full and CIRCLED_RE.match(full[0]))
    
    # Collect all circled-at-start refs sorted by (page, block)
    circled_at_start = []
    for ri, ref in enumerate(all_refs):
        ch = ref[3]
        if CIRCLED_RE.match(ch) and len(ch) == 1:
            if block_is_start.get((ref[0], ref[1]), False):
                num = int(CIRCLE_TO_NUM.get(ch, '0'))
                circled_at_start.append((ri, ref[0], ref[1], num, ch))
    
    circled_at_start.sort(key=lambda x: (x[1], x[2]))  # by page, then block
    
    # Find runs of consecutive numbers (①②③...) within ±2 pages
    to_remove = set()
    i = 0
    while i < len(circled_at_start):
        seq = [circled_at_start[i]]
        j = i + 1
        while j < len(circled_at_start):
            prev = seq[-1]
            curr = circled_at_start[j]
            # Check: sequential numbers AND within 2 pages
            if curr[3] == prev[3] + 1 and abs(curr[1] - prev[1]) <= 2:
                seq.append(curr)
                j += 1
            else:
                break
        if len(seq) >= 2:
            for s in seq:
                to_remove.add(s[0])
        i = j
    
    if to_remove:
        for ri in to_remove:
            all_refs[ri] = (all_refs[ri][0], all_refs[ri][1], all_refs[ri][2],
                           all_refs[ri][3], all_refs[ri][4], all_refs[ri][5],
                           "_removed_")
        new_refs_by_page = defaultdict(list)
        for ri, ref in enumerate(all_refs):
            if ref[6] != "_removed_":
                new_refs_by_page[ref[0]].append(ri)
        return new_refs_by_page
    
    return refs_by_page


def match_footnotes(all_refs, all_contents, refs_by_page, contents_by_page, patterns=None):
    """Match refs to bodies by pattern_id + normalized number.
    
    For patterns with multi_number_split=True (typically digit references):
      allows sharing — multiple refs can point to the same body (ibid. pattern).
    For patterns with multi_number_split=False (typically circled notes):
      strict one-to-one matching — each body used at most once.
    """
    # Determine sharing per pattern
    sharing_allowed = {}
    if patterns:
        for p in patterns:
            sharing_allowed[p["id"]] = p.get("multi_number_split", False)
    
    refs_by_pid = defaultdict(list)
    for ri, ref in enumerate(all_refs):
        refs_by_pid[ref[6]].append(ri)
    
    matched = []
    
    for pid in refs_by_pid:
        allow_share = sharing_allowed.get(pid, False)
        content_used = set()  # one-to-one tracking
        body_consumed = {}    # sharing tracking
        
        for ri in refs_by_pid[pid]:
            ref = all_refs[ri]
            rp, norm_n = ref[0], ref[4]
            
            best = None
            for dp in [0, -1, 1, -2, 2, -3, 3, -4, 4]:
                for ci in contents_by_page.get(rp + dp, []):
                    ct = all_contents[ci]
                    if ct[2] != norm_n or ct[4] != pid:
                        continue
                    
                    if allow_share:
                        # Sharing mode: multiple refs can share same body
                        bodies_before = sum(1 for cj in contents_by_page.get(ct[0], [])
                                           if cj <= ci and all_contents[cj][2] == norm_n
                                           and all_contents[cj][4] == pid)
                        key = (ct[0], ct[2], pid)
                        consumed = body_consumed.get(key, 0)
                        if consumed <= bodies_before:
                            best = ci
                            if consumed < bodies_before:
                                body_consumed[key] = bodies_before
                            break
                    else:
                        # One-to-one: first-come-first-served
                        if ci not in content_used:
                            best = ci
                            content_used.add(ci)
                            break
                
                if best is not None:
                    break
            
            if best is not None:
                matched.append((ri, best))
    
    used_ci = {ci for _, ci in matched}
    unmatched = [ci for ci in range(len(all_contents)) if ci not in used_ci]
    
    return matched, unmatched


# ── Convert mode: HTML generation ───────────────────────────

def _classify_toc_line(line):
    """Classify a TOC line as 'toc-part', 'toc-section', or 'toc-chapter'.
    Works for both Chinese and English books."""
    # Chinese Part headers: 第一部分, 第二部分, ...
    if re.match(r'第[一二三四五六七八九十百]+部分', line):
        return 'toc-part'
    # English Part headers: Part I, Part II, PART ONE, ...
    if re.match(r'(Part|PART)\s+([IVX]+|\w+)', line):
        return 'toc-part'
    # Chinese section headers: 后记, 参考文献, 附录, ...
    if re.match(r'(后记|後記|参考文献|參考文獻|附录|附錄|索引)\b', line):
        return 'toc-section'
    # English section headers
    if re.match(r'(Epilogue|Afterword|Bibliography|References|Appendix|Index)\b', line, re.IGNORECASE):
        return 'toc-section'
    # Default: chapter entry
    return 'toc-chapter'


def build_html(all_pages, all_refs, all_contents, matched, chapter_ranges,
               image_map, img_placement, cover_img_name, title, author,
               skip_pages, css, footnote_config):
    """Generate content XHTML. footnote_config drives display."""
    
    ftypes = footnote_config.get("types", [])
    display_order = footnote_config.get("display_order", [t["id"] for t in ftypes])
    numbering = footnote_config.get("numbering", "per_chapter")
    
    # Build lookup: (abs_page, block_idx, item_idx or raw_char) → (global_num, text, pid)
    ref_to_fn = defaultdict(dict)  # pid → {(ap, bi, ci): (gn, text)}
    text_fn_map = defaultdict(dict)  # pid → {(ap, bi, raw): (gn, text)}
    gn_counters = defaultdict(int)  # pid → counter
    
    for ri, ci in matched:
        ref = all_refs[ri]
        ct = all_contents[ci]
        pid = ref[6]
        rp, rbi, rci, raw_n = ref[0], ref[1], ref[2], ref[3]
        ct_clean = re.sub(r'^[①②③④⑤⑥⑦⑧⑨⑩\d]+\s*', '', ct[3])
        
        gn_counters[pid] += 1
        gn = gn_counters[pid]
        
        if rci == -1:
            text_fn_map[pid][(rp, rbi, raw_n)] = (gn, ct_clean)
        else:
            ref_to_fn[pid][(rp, rbi, rci)] = (gn, ct_clean)
    
    # Build display helper per type
    type_info = {t["id"]: t for t in ftypes}
    for t in ftypes:
        t.setdefault("display_style", "bracket")
        t.setdefault("label", t["id"])
        t.setdefault("anchor_prefix", "fn_" + t["id"] + "_")
    
    def render_ref(style, gn, pid):
        """Render a footnote reference in the text."""
        ti = type_info.get(pid, {})
        prefix = ti.get("anchor_prefix", "fn_")
        if style == "circle":
            display = NUM_TO_CIRCLE.get(str(gn), "({})".format(gn))
            return '<sup><a href="#%s%d" id="%sref%d" epub:type="noteref">%s</a></sup>' % (
                prefix, gn, prefix, gn, display)
        elif style == "bracket":
            return '<sup><a href="#%s%d" id="%sref%d" epub:type="noteref">[%d]</a></sup>' % (
                prefix, gn, prefix, gn, gn)
        elif style == "asterisk":
            stars = "*" * min(gn, 3)
            return '<sup><a href="#%s%d" id="%sref%d" epub:type="noteref">%s</a></sup>' % (
                prefix, gn, prefix, gn, stars)
        else:
            return '<sup><a href="#%s%d" id="%sref%d" epub:type="noteref">[%d]</a></sup>' % (
                prefix, gn, prefix, gn, gn)
    
    def render_body(style, gn, pid):
        """Render a footnote body marker (back-link)."""
        ti = type_info.get(pid, {})
        prefix = ti.get("anchor_prefix", "fn_")
        if style == "circle":
            return NUM_TO_CIRCLE.get(str(gn), "({})".format(gn))
        elif style == "bracket":
            return "[%d]" % gn
        elif style == "asterisk":
            return "*" * min(gn, 3)
        else:
            return "[%d]" % gn
    
    # ── Build HTML ──
    parts = ['<?xml version="1.0" encoding="UTF-8"?>', '<!DOCTYPE html>',
             '<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" xml:lang="zh-CN">',
             '<head><meta charset="UTF-8"/>', '<title>%s</title>' % html.escape(title),
             '<style>%s</style>' % css, '</head>', '<body>']
    
    # Cover
    parts.append('<div class="cover-image"><img src="images/%s" alt="封面" style="max-width:100%%;height:auto;"/></div>' % cover_img_name)
    parts.append('<div class="title-page"><h1>%s</h1><p class="author">%s 著</p></div>' % (html.escape(title), html.escape(author)))
    
    for ch_idx, (ch_name, ch_start, ch_end, is_cover) in enumerate(chapter_ranges):
        if is_cover:
            continue
        ch_id = "ch%d" % (ch_idx + 1)
        parts.append('<h1 id="%s">%s</h1>' % (ch_id, html.escape(ch_name)))
        
        # ── TOC chapter detection (language-agnostic) ──
        toc_keywords = ['目录', '目錄', 'Contents', 'Table of Contents', '目次']
        is_toc_chapter = any(kw in ch_name for kw in toc_keywords)
        
        # Fallback: content-based detection — if chapter has many short
        # lines matching chapter-number patterns, treat it as TOC
        _toc_content_check_done = False
        
        # Separate chapter footnote accumulators per type
        chapter_fns = {pid: [] for pid in [t["id"] for t in ftypes]}
        first_para_skipped = False
        
        for pdata in all_pages:
            ap = pdata["abs_page"]
            if ap < ch_start or ap > ch_end or ap in skip_pages:
                continue
            
            for bi, b in enumerate(pdata["blocks"]):
                t = b.get("type", "?")
                
                if t == "title":
                    ck = "title_content"
                    text = "".join(it.get("content", "") for it in b.get("content", {}).get(ck, [])
                                   if isinstance(it, dict))
                    clean = text.strip()
                    if clean and "CIP" not in clean:
                        # Skip if this title duplicates the chapter name
                        ch_norm = re.sub(r'\s+', '', ch_name)
                        t_norm = re.sub(r'\s+', '', clean)
                        if not (t_norm == ch_norm or (len(t_norm) >= 2 and t_norm in ch_norm)):
                            tag = "h2" if b.get("content", {}).get("level", 1) <= 1 else "h3"
                            parts.append('<%s>%s</%s>' % (tag, html.escape(clean), tag))
                
                elif t == "paragraph":
                    items = b.get("content", {}).get("paragraph_content", [])
                    if not items:
                        continue
                    para_parts = []
                    
                    for ci, item in enumerate(items):
                        if not isinstance(item, dict):
                            continue
                        
                        if item.get("type") == "equation_inline":
                            raw = item.get("content", "").strip()
                            m = re.match(r'\^\{([^}]+)\}', raw)
                            inner = m.group(1) if m else raw
                            
                            # Try each pattern type
                            matched_any = False
                            for tinfo in ftypes:
                                pid = tinfo["id"]
                                key = (ap, bi, ci)
                                if key in ref_to_fn.get(pid, {}):
                                    gn, ft = ref_to_fn[pid][key]
                                    para_parts.append(render_ref(tinfo.get("display_style", "bracket"), gn, pid))
                                    chapter_fns[pid].append((gn, ft))
                                    matched_any = True
                                    break
                            if not matched_any:
                                para_parts.append(html.escape(raw))
                        
                        elif item.get("type") == "text":
                            ic = item.get("content", "")
                            # Collect all marker positions across all types
                            markers_pos = []
                            for tinfo in ftypes:
                                pid = tinfo["id"]
                                mr = tinfo.get("_text_re")
                                if mr is None:
                                    # Build from marker_regex
                                    mrs = tinfo.get("marker_regex", "")
                                    if mrs:
                                        mr = re.compile(mrs)
                                        tinfo["_text_re"] = mr
                                if mr:
                                    for m in mr.finditer(ic):
                                        markers_pos.append((m.start(), m.end(), pid, m.group(1) if m.lastindex else m.group(0)))
                            markers_pos.sort(key=lambda x: x[0])
                            
                            if markers_pos:
                                last = 0
                                for start, end, pid, mval in markers_pos:
                                    para_parts.append(html.escape(ic[last:start]))
                                    key = (ap, bi, mval)
                                    if key in text_fn_map.get(pid, {}):
                                        gn, ft = text_fn_map[pid][key]
                                        tinfo = type_info.get(pid, {})
                                        para_parts.append(render_ref(tinfo.get("display_style", "bracket"), gn, pid))
                                        chapter_fns[pid].append((gn, ft))
                                    else:
                                        para_parts.append(html.escape(ic[start:end]))
                                    last = end
                                para_parts.append(html.escape(ic[last:]))
                            else:
                                para_parts.append(html.escape(ic))
                    
                    pt = "".join(para_parts).strip()
                    if pt:
                        if not first_para_skipped:
                            first_para_skipped = True
                            clean = re.sub(r'<[^>]+>', '', pt).strip()
                            short = ch_name.split()[-1] if ' ' in ch_name else ch_name
                            if clean == ch_name or clean == short:
                                continue
                        # ── TOC formatting: split multi-line TOC blocks ──
                        if is_toc_chapter:
                            clean_toc = re.sub(r'<[^>]+>', '', pt).strip()
                            lines = [l.strip() for l in clean_toc.split('\n') if l.strip()]
                            # Detect if this paragraph looks like multi-line TOC content
                            _has_cn_chapter = any(re.match(r'第[一二三四五六七八九十百]+章', l) for l in lines)
                            _has_en_chapter = any(re.match(r'\d+\.\s+\w', l) for l in lines)
                            if len(lines) >= 2 and (_has_cn_chapter or _has_en_chapter):
                                # Multi-line TOC block → split and tag each line
                                for line in lines:
                                    cls = _classify_toc_line(line)
                                    parts.append('<p class="%s">%s</p>' % (cls, html.escape(line)))
                            else:
                                # Single-line TOC entry
                                cls = _classify_toc_line(clean_toc)
                                parts.append('<p class="%s">%s</p>' % (cls, pt))
                        else:
                            # Not a TOC chapter → render as normal paragraph.
                            # (If a TOC went undetected, write a project-specific
                            #  post-processing script to fix the EPUB.)
                            parts.append('<p>%s</p>' % pt)
                
                elif t == "image":
                    bbox = b.get("bbox", [])
                    w, h = (bbox[2] - bbox[0]) if bbox else 0, (bbox[3] - bbox[1]) if bbox else 0
                    if w <= 100 and h <= 100:
                        continue
                    key = (ap, bi)
                    if key in img_placement:
                        info = img_placement[key]
                        parts.append('<figure><img src="images/%s" alt=""/></figure>' % info["new_name"])
        
        # ── Merge broken paragraphs (page-break artifacts) ──
        parts = merge_broken_paragraphs(parts)
        # Apply the merge result back to our mutable list reference
        # (parts is a local variable that we can rebind at chapter level)
        
        # ── Render footnote sections in display_order ──
        for pid in display_order:
            fns = chapter_fns.get(pid, [])
            if not fns:
                continue
            fns.sort(key=lambda x: x[0])
            tinfo = type_info.get(pid, {})
            label = tinfo.get("label", pid)
            style = tinfo.get("display_style", "bracket")
            prefix = tinfo.get("anchor_prefix", "fn_")
            
            parts.append('<div class="fn-section"><h3>%s</h3>' % html.escape(label))
            for gn, ft in fns:
                marker = render_body(style, gn, pid)
                parts.append('<aside id="%s%d" epub:type="footnote"><p><a href="#%sref%d">%s</a> %s</p></aside>' % (
                    prefix, gn, prefix, gn, marker, html.escape(ft)))
            parts.append('</div>')
    
    parts.append('</body></html>')
    return "\n".join(parts)


# ── EPUB packaging ──────────────────────────────────────────

def generate_opf(image_map, cover_img_name, title, author):
    img_items = '    <item id="cover-img" href="images/%s" media-type="image/jpeg" properties="cover-image"/>\n' % cover_img_name
    for (_, _), info in image_map.items():
        n = info["new_name"]
        if n == cover_img_name:
            continue
        rid = "img_%s" % n.replace('.jpg', '')
        img_items += '    <item id="%s" href="images/%s" media-type="image/jpeg"/>\n' % (rid, n)
    return '''<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://www.idpf.org/2007/opf" unique-identifier="book-id" version="3.0" xml:lang="zh-CN">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:title>%s</dc:title><dc:creator>%s</dc:creator><dc:language>zh-CN</dc:language>
    <dc:identifier id="book-id">urn:uuid:mineru-epub-%s</dc:identifier>
    <dc:date>%s</dc:date>
    <meta property="dcterms:modified">%s</meta><meta name="cover" content="cover-img"/>
  </metadata>
  <manifest>
    <item id="cover-page" href="cover.xhtml" media-type="application/xhtml+xml"/>
    <item id="content" href="content.xhtml" media-type="application/xhtml+xml"/>
    <item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>
    <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>
%s  </manifest>
  <spine toc="ncx"><itemref idref="cover-page" linear="yes"/><itemref idref="content"/></spine>
</package>''' % (html.escape(title), html.escape(author),
           datetime.now().strftime('%Y%m%d%H%M%S'),
           datetime.now().strftime('%Y-%m-%d'),
           datetime.now().strftime('%Y-%m-%dT%H:%M:%SZ'), img_items)


def generate_nav(html_content):
    chapters = re.findall(r'<h1 id="(ch\d+)">([^<]+)</h1>', html_content)
    items = "\n".join('      <li><a href="content.xhtml#%s">%s</a></li>' % (cid, cname) for cid, cname in chapters)
    return '''<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" xml:lang="zh-CN">
<head><meta charset="UTF-8"/><title>目录</title></head>
<body><nav epub:type="toc" id="toc"><h1>目录</h1><ol>%s</ol></nav></body></html>''' % items


def generate_ncx(html_content, title, author):
    chapters = re.findall(r'<h1 id="(ch\d+)">([^<]+)</h1>', html_content)
    pts = []
    for i, (cid, cname) in enumerate(chapters, 1):
        pts.append('    <navPoint id="navpoint-%d" playOrder="%d">\n      <navLabel><text>%s</text></navLabel>\n      <content src="content.xhtml#%s"/>\n    </navPoint>' % (i, i, cname, cid))
    return '''<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ncx PUBLIC "-//NISO//DTD ncx 2005-1//EN" "http://www.daisy.org/z3986/2005/ncx-2005-1.dtd">
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">
  <head><meta name="dtb:uid" content="urn:uuid:book"/><meta name="dtb:depth" content="1"/></head>
  <docTitle><text>%s</text></docTitle><docAuthor><text>%s</text></docAuthor>
  <navMap>%s</navMap></ncx>''' % (html.escape(title), html.escape(author), "\n".join(pts))


def generate_cover_page(cover_img_name, cw, ch):
    return '''<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" xml:lang="zh-CN">
<head><meta charset="UTF-8"/><title>封面</title>
<style>body{margin:0;padding:0;text-align:center;}</style></head>
<body><div style="width:100%%;height:100%%;">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
     width="100%%" height="100%%" viewBox="0 0 %d %d" preserveAspectRatio="xMidYMid meet">
<image xlink:href="images/%s" width="%d" height="%d"/></svg></div></body></html>''' % (cw, ch, cover_img_name, cw, ch)


def process_images(part_dirs, image_dir):
    image_map = {}
    for part_dir in part_dirs:
        imgs_path = Path(part_dir) / "images"
        if not imgs_path.exists():
            continue
        md_files = list(Path(part_dir).glob("full.md"))
        md = md_files[0].read_text() if md_files else ""
        img_refs = re.findall(r'!\[\]\(images/([^)]+)\)', md)
        for orig in img_refs:
            src = imgs_path / orig
            if not src.exists() or not should_include_image(src):
                continue
            seq = len(image_map) + 1
            new_name = "img_%03d.jpg" % seq
            dst = image_dir / new_name
            w, h = compress_image(src, dst)
            image_map[(part_dir, orig)] = {"new_name": new_name, "width": w, "height": h}
    return image_map


def build_image_placement(all_pages, image_map):
    queues = defaultdict(list)
    for (part_dir, _), info in image_map.items():
        queues[part_dir].append(info)
    qi = {k: 0 for k in queues}
    placement = {}
    for pdata in all_pages:
        for bi, b in enumerate(pdata["blocks"]):
            if b.get("type") != "image":
                continue
            bbox = b.get("bbox", [])
            w, h = (bbox[2] - bbox[0]) if bbox else 0, (bbox[3] - bbox[1]) if bbox else 0
            if w <= 100 and h <= 100 or pdata["abs_page"] == 1:
                continue
            queue = queues.get(pdata.get("label", ""), [])
            idx = qi.get(pdata.get("label", ""), 0)
            if idx < len(queue):
                placement[(pdata["abs_page"], bi)] = queue[idx]
                qi[pdata["label"]] = idx + 1
    return placement


def build_chapters(all_pages, chapter_config):
    chapters_final = []
    for ch in chapter_config:
        name = ch.get("name")
        start = ch.get("page")
        if start is not None:
            chapters_final.append((name, start, ch.get("is_cover", False)))
    chapters_final.sort(key=lambda x: x[1])
    max_page = all_pages[-1]["abs_page"]
    ranges = []
    for i, (name, start, is_cover) in enumerate(chapters_final):
        end = chapters_final[i + 1][1] - 1 if i + 1 < len(chapters_final) else max_page
        ranges.append((name, start, end, is_cover))
    return ranges


def write_epub(epub_path, html_content, image_map, cover_img_name, title, author, work_dir):
    opf = generate_opf(image_map, cover_img_name, title, author)
    nav = generate_nav(html_content)
    ncx = generate_ncx(html_content, title, author)
    cover_path = work_dir / "images" / cover_img_name
    cw, ch = Image.open(cover_path).size if cover_path.exists() else (800, 1200)
    cover_page = generate_cover_page(cover_img_name, cw, ch)
    
    container = '<?xml version="1.0"?>\n<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">\n  <rootfiles><rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/></rootfiles>\n</container>'
    
    with zipfile.ZipFile(epub_path, 'w', zipfile.ZIP_DEFLATED) as zf:
        zf.writestr('mimetype', 'application/epub+zip', compress_type=zipfile.ZIP_STORED)
        zf.writestr('META-INF/container.xml', container)
        zf.writestr('OEBPS/content.opf', opf)
        zf.writestr('OEBPS/cover.xhtml', cover_page)
        zf.writestr('OEBPS/content.xhtml', html_content)
        zf.writestr('OEBPS/nav.xhtml', nav)
        zf.writestr('OEBPS/toc.ncx', ncx)
        for (_, _), info in image_map.items():
            src = work_dir / "images" / info["new_name"]
            zf.write(str(src), 'OEBPS/images/%s' % info["new_name"])
        cover_src = work_dir / "images" / cover_img_name
        if cover_src.exists():
            zf.write(str(cover_src), 'OEBPS/images/%s' % cover_img_name)
    
    return epub_path


# ── Main ────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Mineru -> EPUB Converter v2")
    parser.add_argument("--profile", action="store_true", help="Detect footnote patterns")
    parser.add_argument("--convert", action="store_true", help="Generate EPUB")
    parser.add_argument("--input-dir", help="Single Mineru output directory")
    parser.add_argument("--parts", nargs="+", help="Multiple Mineru output directories")
    parser.add_argument("--config", help="Chapter config JSON")
    parser.add_argument("--footnote-config", help="Footnote config JSON (from --profile + LLM)")
    parser.add_argument("--output", help="Output EPUB path (required for --convert)")
    parser.add_argument("--title", default="Untitled", help="Book title")
    parser.add_argument("--author", default="Unknown", help="Book author")
    parser.add_argument("--cover-pdf", help="PDF for cover extraction")
    parser.add_argument("--cover-image", help="Existing cover image")
    parser.add_argument("--css", help="Custom CSS file")
    parser.add_argument("--skip-pages", nargs="*", type=int, default=[], help="Pages to skip")
    parser.add_argument("--work-dir", help="Working directory")
    args = parser.parse_args()
    
    if args.input_dir:
        part_dirs = [args.input_dir]
    elif args.parts:
        part_dirs = args.parts
    else:
        print("ERROR: --input-dir or --parts required")
        sys.exit(1)
    
    # ── Profile mode ──
    if args.profile:
        all_pages = load_pages(part_dirs)
        profile = profile_footnotes(all_pages)
        print(json.dumps(profile, ensure_ascii=False, indent=2))
        return
    
    # ── Convert mode ──
    if args.convert:
        if not args.output:
            print("ERROR: --output required for --convert")
            sys.exit(1)
        if not args.footnote_config:
            print("ERROR: --footnote-config required for --convert (run --profile first)")
            sys.exit(1)
        
        with open(args.footnote_config) as f:
            footnote_config = json.load(f)
        
        work_dir = Path(args.work_dir) if args.work_dir else Path(args.output).parent / "mineru_epub_work"
        work_dir.mkdir(parents=True, exist_ok=True)
        (work_dir / "images").mkdir(exist_ok=True)
        
        # Chapter config
        if args.config:
            with open(args.config) as f:
                config = json.load(f)
            chapter_config = config.get("chapters", [])
            skip_pages = set(config.get("skip_pages", args.skip_pages))
        else:
            all_pages = load_pages(part_dirs)
            auto_chapters = []
            for pdata in all_pages:
                for b in pdata["blocks"]:
                    if b.get("type") == "title":
                        items = b.get("content", {}).get("title_content", [])
                        text = "".join(it.get("content", "") for it in items if isinstance(it, dict)).strip()
                        if text and len(text) < 80:
                            auto_chapters.append({"name": text, "page": pdata["abs_page"]})
            chapter_config = auto_chapters
            skip_pages = set(args.skip_pages)
        
        css = DEFAULT_CSS
        if args.css:
            css = Path(args.css).read_text()
        
        # Build patterns from footnote_config
        patterns = []
        for t in footnote_config.get("types", []):
            pid = t["id"]
            mr = t.get("marker_regex", "")
            mer = t.get("marker_eq_regex", "")
            bpr = t.get("body_prefix_regex", "")
            mns = t.get("multi_number_split", False)
            patterns.append({
                "id": pid,
                "marker_regex": mr,
                "marker_eq_regex": mer,
                "body_prefix_regex": bpr,
                "multi_number_split": mns,
            })
        
        print("=" * 60)
        print("  Mineru → EPUB: %s" % args.title)
        print("=" * 60)
        
        # 1. Load
        print("\n[1/6] Loading Mineru data...")
        all_pages = load_pages(part_dirs)
        print("  %d pages from %d part(s)" % (len(all_pages), len(part_dirs)))
        
        # 2. Images
        print("\n[2/6] Processing images...")
        image_map = process_images(part_dirs, work_dir / "images")
        img_placement = build_image_placement(all_pages, image_map)
        print("  %d images, %d placed" % (len(image_map), len(img_placement)))
        
        cover_img_name = "cover.jpg"
        cover_dst = work_dir / "images" / cover_img_name
        if args.cover_image and Path(args.cover_image).exists():
            w, h = compress_image(Path(args.cover_image), cover_dst, max_width=1400, quality=80)
        elif args.cover_pdf and Path(args.cover_pdf).exists():
            import pypdfium2 as pdfium
            pdf = pdfium.PdfDocument(args.cover_pdf)
            bitmap = pdf[0].render(scale=2.0)
            img = bitmap.to_pil()
            w, h = img.size
            if w > 1400:
                img = img.resize((1400, int(h * 1400 / w)), Image.LANCZOS)
            img.save(cover_dst, 'JPEG', quality=80, optimize=True)
            pdf.close()
        
        # 3. Footnotes
        print("\n[3/6] Extracting and matching footnotes...")
        all_refs, all_contents, rbp, cbp = extract_footnotes(all_pages, patterns)
        # Filter enumeration markers: sequential circled numbers at block starts
        rbp = filter_enumeration_refs(all_refs, all_pages, rbp)
        matched, unmatched = match_footnotes(all_refs, all_contents, rbp, cbp, patterns)
        print("  %d refs, %d contents, %d matched" % (len(all_refs), len(all_contents), len(matched)))
        if unmatched:
            print("  %d unmatched contents" % len(unmatched))
        
        # 4. Chapters
        print("\n[4/6] Building chapter structure...")
        chapters = build_chapters(all_pages, chapter_config)
        print("  %d chapters" % len(chapters))
        
        # 5. HTML
        print("\n[5/6] Generating XHTML...")
        html_content = build_html(all_pages, all_refs, all_contents, matched, chapters,
                                  image_map, img_placement, cover_img_name,
                                  args.title, args.author, skip_pages, css, footnote_config)
        print("  %d chars" % len(html_content))
        
        # 6. EPUB
        print("\n[6/6] Packaging EPUB...")
        epub_path = write_epub(args.output, html_content, image_map, cover_img_name,
                              args.title, args.author, work_dir)
        size_kb = Path(epub_path).stat().st_size / 1024
        print("\n✅ %s (%.0f KB)" % (epub_path, size_kb))
        
        # Verify
        with zipfile.ZipFile(epub_path, 'r') as zf:
            h = zf.read('OEBPS/content.xhtml').decode('utf-8')
            chs = len(re.findall(r'<h1 id="ch', h))
            imgs = len(re.findall(r'<img src="images/', h))
            total_refs = len(re.findall(r'epub:type="noteref"', h))
            total_fns = len(re.findall(r'epub:type="footnote"', h))
            for tinfo in footnote_config.get("types", []):
                pid = tinfo["id"]
                prefix = tinfo.get("anchor_prefix", "fn_" + pid + "_")
                r = len(re.findall(r'id="%sref\d+"' % prefix, h))
                f = len(re.findall(r'id="%s\d+"' % prefix, h))
                print("  %s: %d refs / %d bodies" % (tinfo.get("label", pid), r, f))
            print("  Chapters: %d | Images: %d" % (chs, imgs))
            print("  %s" % ("✅ All footnote links valid" if total_refs == total_fns else "⚠️ Mismatch"))
        return
    
    # ── No mode specified ──
    print("Specify --profile (to detect footnote patterns) or --convert (to generate EPUB)")
    print("See SKILL.md for the full workflow.")


if __name__ == "__main__":
    main()
